#!/bin/sh

cd ~/work/crab$1

i3-msg split h
i3-msg exec "alacritty --working-directory ~/work/crab$1/appserver"
sleep 0.3

i3-msg split v
i3-msg exec "alacritty --working-directory ~/work/crab$1/renderer"
sleep 0.3

i3-msg split h
i3-msg exec "alacritty --working-directory ~/work/crab$1/jvm-link"
sleep 0.3

i3-msg focus up
i3-msg split h
i3-msg exec "alacritty --working-directory ~/work/crab$1/auth"
sleep 0.3

i3-msg focus left
i3-msg focus left
i3-msg split v
i3-msg exec "alacritty --working-directory ~/work/crab$1/webserver"
sleep 0.3

if test -z "$1" 
then
  second_workspace=2
else
  second_workspace="$(($1*3-1))"
fi

i3-msg workspace $second_workspace
i3-msg exec "alacritty --working-directory ~/work/crab$1"

clear
